name: profile
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^0.2.0
  universal_html: 1.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.0.0
  mockito: ^4.1.1
  test: ^1.9.4

flutter:
  assets:
    - assets/

  fonts:
   - family:  Font
     fonts:
      - asset: assets/fonts/Font.ttf
