name: profile
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^0.2.0
  universal_html: 1.1.11

dev_dependencies:
  pedantic: ^1.0.0

flutter:
  assets:
    - assets/page.ico
    - assets/tomek.png
    - assets/manifest.json
    - assets/droidcon.jpg
    - assets/tomek_round.png

  fonts:
   - family:  Font
     fonts:
      - asset: assets/fonts/Font.ttf
