/// Flutter icons Font
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Font
///      fonts:
///       - asset: fonts/Font.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:profile/shared/material_import.dart';

class Font {
  Font._();

  static const _kFontFam = 'Font';

  static const IconData mail = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xf099, fontFamily: _kFontFam);
  static const IconData github_circled =
      const IconData(0xf09b, fontFamily: _kFontFam);
  static const IconData linkedin =
      const IconData(0xf0e1, fontFamily: _kFontFam);
  static const IconData skype = const IconData(0xf17e, fontFamily: _kFontFam);
  static const IconData medium = const IconData(0xf23a, fontFamily: _kFontFam);
}
